# fly.toml app configuration file generated for forgetnomore on 2023-08-29T14:13:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "forgetnomore"
primary_region = "cdg"

[build]

[[statics]]
guest_path = "/dist/index.html"
url_prefix = "/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
